brew cask install google-chrome
brew cask install spotify
brew cask install iterm2
brew cask install flux
brew cask install vlc
brew cask install tunnelblick
brew cask install google-backup-and-sync
brew cask install amazon-drive
brew cask install adobe-creative-cloud
brew cask install battle-net
brew cask install steam
brew cask install discord
brew cask install slack
brew cask install skype
brew cask install authy
brew cask install nordvpn
